permalink: /:year/:month/:day/:title.html
name: "[w«êth sky]"
markdown: kramdown
hightlighter: rouge

author: "Ray"
atom-baseurl: "http://blog.raypp.cn"
disqus: "withsky"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

